services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: always
    command: -- tail -f /dev/null
    environment:
      VERSION: "10"
      USERNAME: "MASTER"
      PASSWORD: "admin@123"
      RAM_SIZE: "4G"
      CPU_CORES: "16"
      DISK_SIZE: "32G"
      DISK2_SIZE: "8G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /tmp:/storage
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
